{
  "openapi" : "3.0.0",
  "info" : {
    "version" : "1.0",
    "title" : "IPH API",
    "description" : "The IPH API services the International Performance Hub that is a comprehensive platform for public users to access and engage on global performance indicators."
  },
  "paths" : {
    "/summary" : {
      "get" : {
        "summary" : "List of key pillars and top five KPIs",
        "description" : "Return key pillars and the top five KPIs for each pillar that includes their latest value, last measured year, global ranking and change in rank from previous measurement",
        "responses" : {
          "200" : {
            "description" : "return key pillars and top five KPIs for each pillar",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "isClassic" : {
                      "type" : "boolean",
                      "description" : "indicates if the classic view data is available"
                    },
                    "isSdg" : {
                      "type" : "boolean",
                      "description" : "indicates if the SDG view data is available"
                    },
                    "classic" : {
                      "type" : "array",
                      "description" : "collection of all elements (key pillars and top KPIs) in the classic view",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "pillarId" : {
                            "type" : "string",
                            "description" : "unique identification number of the pillar"
                          },
                          "pillarName" : {
                            "type" : "string",
                            "description" : "the name of the pillar"
                          },
                          "pillarIconSM" : {
                            "type" : "string",
                            "description" : "the icon associated with the pillar - small sized in base64 format"
                          },
                          "kpis" : {
                            "$ref" : "#/components/schemas/kpis"
                          }
                        }
                      }
                    },
                    "sdg" : {
                      "type" : "array",
                      "description" : "collection of all elements (key pillars and top KPIs) in the SDG view",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "pillarId" : {
                            "type" : "string",
                            "description" : "unique identification number of the pillar"
                          },
                          "pillarName" : {
                            "type" : "string",
                            "description" : "the name of the pillar"
                          },
                          "pillarIconSM" : {
                            "type" : "string",
                            "description" : "the icon associated with the pillar - small sized in base64 format"
                          },
                          "kpis" : {
                            "$ref" : "#/components/schemas/kpis"
                          }
                        }
                      }
                    }
                  },
                  "example" : {
                    "isClassic" : true,
                    "isSdg" : true,
                    "classic" : [ {
                      "pillarId" : "2",
                      "pillarName" : "الإعلام",
                      "pillarIconSM" : "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxODIuODQ4IiBoZWlnaHQ9IjEyOCIgdmlld0JveD0iMCAwIDE4Mi44NDggMTI4Ij4KICA8ZyBpZD0iaGVhbHRoIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLjA4MyAtMC4wMDUpIj4KICAgIDxwYXRoIGlkPSJfUGF0aF8zIiBkYXRhLW5hbWU9IiBQYXRoIDMiIGQ9Ik0zNDIuMTMyLDI1MS42ODJjMC03LjY3Ny00LjkxNS0xMy45MTYtMTIuMzktMTMuOTE2LTMuNzI5LDAtOC4yMzYsNC4wOTMtMTAuNjc5LDYuNi0yLjQ1NC0yLjUyMi02LjY0OC02LjYwOS0xMC4zNzEtNi42MDktNy40NTksMC0xMi42OTIsNi4yMjgtMTIuNjkyLDEzLjkyMmExNC4wNjcsMTQuMDY3LDAsMCwwLDMuOTU4LDkuODI0aDBsMTkuMTMzLDE5LjE2MSwxOS4xLTE5LjEzOGgwQTE0LjA2NywxNC4wNjcsMCwwLDAsMzQyLjEzMiwyNTEuNjgyWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE1OS4zNjggLTE4My45NTQpIiBmaWxsPSIjZmZmIi8+CiAgICA8ZyBpZD0iX0dyb3VwXyIgZGF0YS1uYW1lPSIgR3JvdXAgIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMC4wODMgMC4wMDUpIj4KICAgICAgPHBhdGggaWQ9Il9QYXRoXzQiIGRhdGEtbmFtZT0iIFBhdGggNCIgZD0iTTE1Mi44NzksMjY5LjUzNWgtLjJhMy4xMjUsMy4xMjUsMCwwLDEtMi45LTIuNmwtOS43MTctNTYuNi0xNC43MjEsMjcuMjlhMy4xNDIsMy4xNDIsMCwwLDEtNS44NzEtMS4wNDZMMTEzLjIyMSwxOTIuOWwtMTEuNDM0LDI1LjY4YTMuMTUzLDMuMTUzLDAsMCwxLTIuODY4LDEuODczSDU0LjQ4N2EzLjE0MiwzLjE0MiwwLDAsMSwwLTYuMjc5SDk2Ljg3OGwxNS4wNC0zMy44YTMuMTM3LDMuMTM3LDAsMCwxLDUuOTc3LjgxNmw2LjQ0Nyw0NS4wMzEsMTQuNTM3LTI2LjkxNmEzLjE0MiwzLjE0MiwwLDAsMSw1Ljg1OS45NjJsOS4wMDcsNTIuNDExLDMyLjc2OS0xMDguOTA5YTMuMTQyLDMuMTQyLDAsMCwxLDUuODM3LS40NThsMTcuMjYsMzUuNzgzYTMuMTQyLDMuMTQyLDAsMCwxLTUuNTkxLDIuODM1bC0uMDUtLjEwNi0xMy43NDktMjguNTE1TDE1NS44ODEsMjY3LjNhMy4xMzcsMy4xMzcsMCwwLDEtMywyLjIzNloiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC01MS40NzcgLTE0MS41MzUpIiBmaWxsPSIjZmZmIi8+CiAgICA8L2c+CiAgPC9nPgo8L3N2Zz4K",
                      "kpis" : [ {
                        "id" : "202",
                        "name" : "مؤشر حرية الصحافة",
                        "value" : "33.71",
                        "unit" : "نقطة",
                        "year" : "2022",
                        "rank" : "166",
                        "outOf" : "180",
                        "change" : "+2",
                        "scale" : "0-100",
                        "polarity" : "negative",
                        "trend" : [ "49.80", "45.10", "34.50", "35.60", "33.71" ]
                      } ]
                    } ],
                    "sdg" : [ {
                      "pillarId" : "10",
                      "pillarName" : "المالية والاستثمار",
                      "pillarIconSM" : "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMjguMDE0IiBoZWlnaHQ9IjEyOCIgdmlld0JveD0iMCAwIDEyOC4wMTQgMTI4Ij4KICA8ZyBpZD0iRXF1YWxpdHkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDAyIC0wLjAwMikiPgogICAgPHBhdGggaWQ9IlBhdGhfODQzIiBkYXRhLW5hbWU9IlBhdGggODQzIiBkPSJNMjQ5LjAyNSwyNzIuMTlIMjAzLjkxNWEuNTE3LjUxNywwLDAsMC0uNDg3LjU0OFYyODYuM2EuNTE3LjUxNywwLDAsMCwuNDg3LjU0OGg0NS4xMDlhLjUxNy41MTcsMCwwLDAsLjQ4Ny0uNTQ4VjI3Mi43MzhhLjUxNy41MTcsMCwwLDAtLjQ4Ny0uNTQ4IiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMTYyLjQ2NyAtMjAxLjA5KSIgZmlsbD0iI2ZmZiIvPgogICAgPHBhdGggaWQ9IlBhdGhfODQ0IiBkYXRhLW5hbWU9IlBhdGggODQ0IiBkPSJNMjQ5LjAyNSwyMDYuMzhIMjAzLjkxNWEuNTE3LjUxNywwLDAsMC0uNDg3LjU0OHYxMy41NThhLjUxNy41MTcsMCwwLDAsLjQ4Ny41NDhoNDUuMTA5YS41MTcuNTE3LDAsMCwwLC40ODctLjU0OFYyMDYuOTI4YS41MTcuNTE3LDAsMCwwLS40ODctLjU0OCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE2Mi40NjcgLTE2NC4xMjcpIiBmaWxsPSIjZmZmIi8+CiAgICA8cGF0aCBpZD0iUGF0aF84NDUiIGRhdGEtbmFtZT0iUGF0aCA4NDUiIGQ9Ik0yNDkuNjk1LDEzMS43NSwyMjguMDQxLDExMC4xYS4zNzMuMzczLDAsMCwwLS41MjYsMEwyMDUuODYxLDEzMS43NWEuMzczLjM3MywwLDAsMCwuMjYzLjYzNmg0My4zMDhhLjM3My4zNzMsMCwwLDAsLjM3My0uMzczQS4zNjguMzY4LDAsMCwwLDI0OS42OTUsMTMxLjc1WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE2My43NzMgLTEwOS45OSkiIGZpbGw9IiNmZmYiLz4KICAgIDxwYXRoIGlkPSJQYXRoXzg0NiIgZGF0YS1uYW1lPSJQYXRoIDg0NiIgZD0iTTM1MS41NiwyNDkuN2wyMS42NS0yMS42NDlhLjM3Mi4zNzIsMCwwLDAsMC0uNTNoMGwtMjEuNjUtMjEuNjU0YS4zNzcuMzc3LDAsMCwwLS42NC4yNjN2NDMuMzA4YS4zNzcuMzc3LDAsMCwwLC42NC4yNjNaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMjQ1LjMwOCAtMTYzLjc3NykiIGZpbGw9IiNmZmYiLz4KICAgIDxwYXRoIGlkPSJQYXRoXzg0NyIgZGF0YS1uYW1lPSJQYXRoIDg0NyIgZD0iTTIwNS44NDgsMzUxLjU0OSwyMjcuNSwzNzMuMTk0YS4zNzcuMzc3LDAsMCwwLC41MjYsMGgwbDIxLjY1NC0yMS42NTRhLjM3My4zNzMsMCwwLDAsMC0uNTI2LjM2NC4zNjQsMCwwLDAtLjI2Ny0uMTE0aC00My4zYS4zNzMuMzczLDAsMCwwLS4zODEuMzY0QS4zNjguMzY4LDAsMCwwLDIwNS44NDgsMzUxLjU0OVoiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xNjMuNzYgLTI0NS4yOTkpIiBmaWxsPSIjZmZmIi8+CiAgICA8cGF0aCBpZD0iUGF0aF84NDgiIGRhdGEtbmFtZT0iUGF0aCA4NDgiIGQ9Ik0xMzEuNzM4LDIwNS44NjNsLTIxLjY1LDIxLjY1NGEuMzY4LjM2OCwwLDAsMCwwLC41MjZoMGwyMS42NSwyMS42NTRhLjM3My4zNzMsMCwwLDAsLjUzLDAsLjM2OC4zNjgsMCwwLDAsLjExLS4yNjNWMjA2LjEyNmEuMzc3LjM3NywwLDAsMC0uNjQtLjI2M1oiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMDkuOTggLTE2My43NzcpIiBmaWxsPSIjZmZmIi8+CiAgPC9nPgo8L3N2Zz4K",
                      "kpis" : [ {
                        "id" : "1002",
                        "name" : "مؤشر حجم الاستثمار الأجنبي المباشر",
                        "value" : "87",
                        "unit" : "نقطة",
                        "year" : "2021",
                        "rank" : "32",
                        "outOf" : "215",
                        "change" : "+4",
                        "scale" : "number",
                        "polarity" : "positive",
                        "trend" : [ "100", "250", "290", "300", "485" ]
                      } ]
                    } ]
                  }
                }
              }
            }
          },
          "204" : {
            "description" : "No Content"
          }
        }
      }
    },
    "/classic/pillars" : {
      "get" : {
        "summary" : "List of all classic view pillars",
        "description" : "Return all the pillars, the total number of pillars, and KPIs under the classic view",
        "responses" : {
          "200" : {
            "description" : "return list of pillars and summary information of each pillar under classic view",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "pillarsDescription" : {
                      "type" : "string"
                    },
                    "numOfPillars" : {
                      "type" : "string",
                      "description" : "the total number of pillars in the classic view"
                    },
                    "numOfIndicators" : {
                      "type" : "string",
                      "description" : "the total number of indicators in the classic view"
                    },
                    "pillars" : {
                      "type" : "array",
                      "description" : "array of pillars under the classic view",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "id" : {
                            "type" : "string",
                            "description" : "unique identification number of the pillar"
                          },
                          "name" : {
                            "type" : "string",
                            "description" : "the name of the pillar"
                          },
                          "iconLG" : {
                            "type" : "string",
                            "description" : "the icon associated with the pillar - large sized in base64 format"
                          },
                          "totalIndicators" : {
                            "type" : "string",
                            "description" : "total number of indicators under the pillar"
                          }
                        }
                      }
                    }
                  }
                },
                "example" : {
                  "numOfPillars" : "12",
                  "numOfIndicators" : "233",
                  "pillars" : [ {
                    "id" : "1",
                    "name" : "المالية والاستثمار",
                    "iconLG" : "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMjguMDE0IiBoZWlnaHQ9IjEyOCIgdmlld0JveD0iMCAwIDEyOC4wMTQgMTI4Ij4KICA8ZyBpZD0iRXF1YWxpdHkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDAyIC0wLjAwMikiPgogICAgPHBhdGggaWQ9IlBhdGhfODQzIiBkYXRhLW5hbWU9IlBhdGggODQzIiBkPSJNMjQ5LjAyNSwyNzIuMTlIMjAzLjkxNWEuNTE3LjUxNywwLDAsMC0uNDg3LjU0OFYyODYuM2EuNTE3LjUxNywwLDAsMCwuNDg3LjU0OGg0NS4xMDlhLjUxNy41MTcsMCwwLDAsLjQ4Ny0uNTQ4VjI3Mi43MzhhLjUxNy41MTcsMCwwLDAtLjQ4Ny0uNTQ4IiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMTYyLjQ2NyAtMjAxLjA5KSIgZmlsbD0iI2ZmZiIvPgogICAgPHBhdGggaWQ9IlBhdGhfODQ0IiBkYXRhLW5hbWU9IlBhdGggODQ0IiBkPSJNMjQ5LjAyNSwyMDYuMzhIMjAzLjkxNWEuNTE3LjUxNywwLDAsMC0uNDg3LjU0OHYxMy41NThhLjUxNy41MTcsMCwwLDAsLjQ4Ny41NDhoNDUuMTA5YS41MTcuNTE3LDAsMCwwLC40ODctLjU0OFYyMDYuOTI4YS41MTcuNTE3LDAsMCwwLS40ODctLjU0OCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE2Mi40NjcgLTE2NC4xMjcpIiBmaWxsPSIjZmZmIi8+CiAgICA8cGF0aCBpZD0iUGF0aF84NDUiIGRhdGEtbmFtZT0iUGF0aCA4NDUiIGQ9Ik0yNDkuNjk1LDEzMS43NSwyMjguMDQxLDExMC4xYS4zNzMuMzczLDAsMCwwLS41MjYsMEwyMDUuODYxLDEzMS43NWEuMzczLjM3MywwLDAsMCwuMjYzLjYzNmg0My4zMDhhLjM3My4zNzMsMCwwLDAsLjM3My0uMzczQS4zNjguMzY4LDAsMCwwLDI0OS42OTUsMTMxLjc1WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE2My43NzMgLTEwOS45OSkiIGZpbGw9IiNmZmYiLz4KICAgIDxwYXRoIGlkPSJQYXRoXzg0NiIgZGF0YS1uYW1lPSJQYXRoIDg0NiIgZD0iTTM1MS41NiwyNDkuN2wyMS42NS0yMS42NDlhLjM3Mi4zNzIsMCwwLDAsMC0uNTNoMGwtMjEuNjUtMjEuNjU0YS4zNzcuMzc3LDAsMCwwLS42NC4yNjN2NDMuMzA4YS4zNzcuMzc3LDAsMCwwLC42NC4yNjNaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMjQ1LjMwOCAtMTYzLjc3NykiIGZpbGw9IiNmZmYiLz4KICAgIDxwYXRoIGlkPSJQYXRoXzg0NyIgZGF0YS1uYW1lPSJQYXRoIDg0NyIgZD0iTTIwNS44NDgsMzUxLjU0OSwyMjcuNSwzNzMuMTk0YS4zNzcuMzc3LDAsMCwwLC41MjYsMGgwbDIxLjY1NC0yMS42NTRhLjM3My4zNzMsMCwwLDAsMC0uNTI2LjM2NC4zNjQsMCwwLDAtLjI2Ny0uMTE0aC00My4zYS4zNzMuMzczLDAsMCwwLS4zODEuMzY0QS4zNjguMzY4LDAsMCwwLDIwNS44NDgsMzUxLjU0OVoiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xNjMuNzYgLTI0NS4yOTkpIiBmaWxsPSIjZmZmIi8+CiAgICA8cGF0aCBpZD0iUGF0aF84NDgiIGRhdGEtbmFtZT0iUGF0aCA4NDgiIGQ9Ik0xMzEuNzM4LDIwNS44NjNsLTIxLjY1LDIxLjY1NGEuMzY4LjM2OCwwLDAsMCwwLC41MjZoMGwyMS42NSwyMS42NTRhLjM3My4zNzMsMCwwLDAsLjUzLDAsLjM2OC4zNjgsMCwwLDAsLjExLS4yNjNWMjA2LjEyNmEuMzc3LjM3NywwLDAsMC0uNjQtLjI2M1oiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMDkuOTggLTE2My43NzcpIiBmaWxsPSIjZmZmIi8+CiAgPC9nPgo8L3N2Zz4K",
                    "totalIndicators" : "12"
                  }, {
                    "id" : "2",
                    "name" : "الإعلام",
                    "iconLG" : "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMjguMDE0IiBoZWlnaHQ9IjEyOCIgdmlld0JveD0iMCAwIDEyOC4wMTQgMTI4Ij4KICA8ZyBpZD0iRXF1YWxpdHkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDAyIC0wLjAwMikiPgogICAgPHBhdGggaWQ9IlBhdGhfODQzIiBkYXRhLW5hbWU9IlBhdGggODQzIiBkPSJNMjQ5LjAyNSwyNzIuMTlIMjAzLjkxNWEuNTE3LjUxNywwLDAsMC0uNDg3LjU0OFYyODYuM2EuNTE3LjUxNywwLDAsMCwuNDg3LjU0OGg0NS4xMDlhLjUxNy41MTcsMCwwLDAsLjQ4Ny0uNTQ4VjI3Mi43MzhhLjUxNy41MTcsMCwwLDAtLjQ4Ny0uNTQ4IiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMTYyLjQ2NyAtMjAxLjA5KSIgZmlsbD0iI2ZmZiIvPgogICAgPHBhdGggaWQ9IlBhdGhfODQ0IiBkYXRhLW5hbWU9IlBhdGggODQ0IiBkPSJNMjQ5LjAyNSwyMDYuMzhIMjAzLjkxNWEuNTE3LjUxNywwLDAsMC0uNDg3LjU0OHYxMy41NThhLjUxNy41MTcsMCwwLDAsLjQ4Ny41NDhoNDUuMTA5YS41MTcuNTE3LDAsMCwwLC40ODctLjU0OFYyMDYuOTI4YS41MTcuNTE3LDAsMCwwLS40ODctLjU0OCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE2Mi40NjcgLTE2NC4xMjcpIiBmaWxsPSIjZmZmIi8+CiAgICA8cGF0aCBpZD0iUGF0aF84NDUiIGRhdGEtbmFtZT0iUGF0aCA4NDUiIGQ9Ik0yNDkuNjk1LDEzMS43NSwyMjguMDQxLDExMC4xYS4zNzMuMzczLDAsMCwwLS41MjYsMEwyMDUuODYxLDEzMS43NWEuMzczLjM3MywwLDAsMCwuMjYzLjYzNmg0My4zMDhhLjM3My4zNzMsMCwwLDAsLjM3My0uMzczQS4zNjguMzY4LDAsMCwwLDI0OS42OTUsMTMxLjc1WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE2My43NzMgLTEwOS45OSkiIGZpbGw9IiNmZmYiLz4KICAgIDxwYXRoIGlkPSJQYXRoXzg0NiIgZGF0YS1uYW1lPSJQYXRoIDg0NiIgZD0iTTM1MS41NiwyNDkuN2wyMS42NS0yMS42NDlhLjM3Mi4zNzIsMCwwLDAsMC0uNTNoMGwtMjEuNjUtMjEuNjU0YS4zNzcuMzc3LDAsMCwwLS42NC4yNjN2NDMuMzA4YS4zNzcuMzc3LDAsMCwwLC42NC4yNjNaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMjQ1LjMwOCAtMTYzLjc3NykiIGZpbGw9IiNmZmYiLz4KICAgIDxwYXRoIGlkPSJQYXRoXzg0NyIgZGF0YS1uYW1lPSJQYXRoIDg0NyIgZD0iTTIwNS44NDgsMzUxLjU0OSwyMjcuNSwzNzMuMTk0YS4zNzcuMzc3LDAsMCwwLC41MjYsMGgwbDIxLjY1NC0yMS42NTRhLjM3My4zNzMsMCwwLDAsMC0uNTI2LjM2NC4zNjQsMCwwLDAtLjI2Ny0uMTE0aC00My4zYS4zNzMuMzczLDAsMCwwLS4zODEuMzY0QS4zNjguMzY4LDAsMCwwLDIwNS44NDgsMzUxLjU0OVoiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xNjMuNzYgLTI0NS4yOTkpIiBmaWxsPSIjZmZmIi8+CiAgICA8cGF0aCBpZD0iUGF0aF84NDgiIGRhdGEtbmFtZT0iUGF0aCA4NDgiIGQ9Ik0xMzEuNzM4LDIwNS44NjNsLTIxLjY1LDIxLjY1NGEuMzY4LjM2OCwwLDAsMCwwLC41MjZoMGwyMS42NSwyMS42NTRhLjM3My4zNzMsMCwwLDAsLjUzLDAsLjM2OC4zNjgsMCwwLDAsLjExLS4yNjNWMjA2LjEyNmEuMzc3LjM3NywwLDAsMC0uNjQtLjI2M1oiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMDkuOTggLTE2My43NzcpIiBmaWxsPSIjZmZmIi8+CiAgPC9nPgo8L3N2Zz4K",
                    "totalIndicators" : "15"
                  } ]
                }
              }
            }
          },
          "204" : {
            "description" : "No Content"
          }
        }
      }
    },
    "/sdg/pillars" : {
      "get" : {
        "summary" : "List of all SDG pillars",
        "description" : "Return all the pillars, the total number of pillars, and KPIs under the SDG view",
        "responses" : {
          "200" : {
            "description" : "return list of pillars and summary information of each pillar under SDG view",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "pillarsDescription" : {
                      "type" : "string"
                    },
                    "numOfPillars" : {
                      "type" : "string",
                      "description" : "the total number of pillars in the SDG view"
                    },
                    "numOfIndicators" : {
                      "type" : "string",
                      "description" : "the total number of indicators in the SDG view"
                    },
                    "pillars" : {
                      "type" : "array",
                      "description" : "array of pillars under the SDG view",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "id" : {
                            "type" : "string",
                            "description" : "unique indentification number of the pillar"
                          },
                          "name" : {
                            "type" : "string",
                            "description" : "the name of the pillar"
                          },
                          "iconLG" : {
                            "type" : "string",
                            "description" : "the icon associated with the pillar - large sized in base64 format"
                          },
                          "totalIndicators" : {
                            "type" : "string",
                            "description" : "total number of indicators under the pillar"
                          }
                        }
                      }
                    }
                  }
                },
                "example" : {
                  "numOfPillars" : "11",
                  "numOfIndicators" : "300",
                  "pillars" : [ {
                    "id" : "1",
                    "name" : "حقوق الانسان",
                    "iconLG" : "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMjguMDE0IiBoZWlnaHQ9IjEyOCIgdmlld0JveD0iMCAwIDEyOC4wMTQgMTI4Ij4KICA8ZyBpZD0iRXF1YWxpdHkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDAyIC0wLjAwMikiPgogICAgPHBhdGggaWQ9IlBhdGhfODQzIiBkYXRhLW5hbWU9IlBhdGggODQzIiBkPSJNMjQ5LjAyNSwyNzIuMTlIMjAzLjkxNWEuNTE3LjUxNywwLDAsMC0uNDg3LjU0OFYyODYuM2EuNTE3LjUxNywwLDAsMCwuNDg3LjU0OGg0NS4xMDlhLjUxNy41MTcsMCwwLDAsLjQ4Ny0uNTQ4VjI3Mi43MzhhLjUxNy41MTcsMCwwLDAtLjQ4Ny0uNTQ4IiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMTYyLjQ2NyAtMjAxLjA5KSIgZmlsbD0iI2ZmZiIvPgogICAgPHBhdGggaWQ9IlBhdGhfODQ0IiBkYXRhLW5hbWU9IlBhdGggODQ0IiBkPSJNMjQ5LjAyNSwyMDYuMzhIMjAzLjkxNWEuNTE3LjUxNywwLDAsMC0uNDg3LjU0OHYxMy41NThhLjUxNy41MTcsMCwwLDAsLjQ4Ny41NDhoNDUuMTA5YS41MTcuNTE3LDAsMCwwLC40ODctLjU0OFYyMDYuOTI4YS41MTcuNTE3LDAsMCwwLS40ODctLjU0OCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE2Mi40NjcgLTE2NC4xMjcpIiBmaWxsPSIjZmZmIi8+CiAgICA8cGF0aCBpZD0iUGF0aF84NDUiIGRhdGEtbmFtZT0iUGF0aCA4NDUiIGQ9Ik0yNDkuNjk1LDEzMS43NSwyMjguMDQxLDExMC4xYS4zNzMuMzczLDAsMCwwLS41MjYsMEwyMDUuODYxLDEzMS43NWEuMzczLjM3MywwLDAsMCwuMjYzLjYzNmg0My4zMDhhLjM3My4zNzMsMCwwLDAsLjM3My0uMzczQS4zNjguMzY4LDAsMCwwLDI0OS42OTUsMTMxLjc1WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE2My43NzMgLTEwOS45OSkiIGZpbGw9IiNmZmYiLz4KICAgIDxwYXRoIGlkPSJQYXRoXzg0NiIgZGF0YS1uYW1lPSJQYXRoIDg0NiIgZD0iTTM1MS41NiwyNDkuN2wyMS42NS0yMS42NDlhLjM3Mi4zNzIsMCwwLDAsMC0uNTNoMGwtMjEuNjUtMjEuNjU0YS4zNzcuMzc3LDAsMCwwLS42NC4yNjN2NDMuMzA4YS4zNzcuMzc3LDAsMCwwLC42NC4yNjNaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMjQ1LjMwOCAtMTYzLjc3NykiIGZpbGw9IiNmZmYiLz4KICAgIDxwYXRoIGlkPSJQYXRoXzg0NyIgZGF0YS1uYW1lPSJQYXRoIDg0NyIgZD0iTTIwNS44NDgsMzUxLjU0OSwyMjcuNSwzNzMuMTk0YS4zNzcuMzc3LDAsMCwwLC41MjYsMGgwbDIxLjY1NC0yMS42NTRhLjM3My4zNzMsMCwwLDAsMC0uNTI2LjM2NC4zNjQsMCwwLDAtLjI2Ny0uMTE0aC00My4zYS4zNzMuMzczLDAsMCwwLS4zODEuMzY0QS4zNjguMzY4LDAsMCwwLDIwNS44NDgsMzUxLjU0OVoiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xNjMuNzYgLTI0NS4yOTkpIiBmaWxsPSIjZmZmIi8+CiAgICA8cGF0aCBpZD0iUGF0aF84NDgiIGRhdGEtbmFtZT0iUGF0aCA4NDgiIGQ9Ik0xMzEuNzM4LDIwNS44NjNsLTIxLjY1LDIxLjY1NGEuMzY4LjM2OCwwLDAsMCwwLC41MjZoMGwyMS42NSwyMS42NTRhLjM3My4zNzMsMCwwLDAsLjUzLDAsLjM2OC4zNjgsMCwwLDAsLjExLS4yNjNWMjA2LjEyNmEuMzc3LjM3NywwLDAsMC0uNjQtLjI2M1oiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMDkuOTggLTE2My43NzcpIiBmaWxsPSIjZmZmIi8+CiAgPC9nPgo8L3N2Zz4K",
                    "totalIndicators" : "10"
                  } ]
                }
              }
            }
          },
          "204" : {
            "description" : "No Content"
          }
        }
      }
    },
    "/classic/pillars/{pillar-id}/indicators" : {
      "get" : {
        "summary" : "List of indicators for a specific pillar under the classic view",
        "description" : "Return list of all indicators and summary of key indicators (top five) for a specific pillar under the classic view",
        "parameters" : [ {
          "in" : "path",
          "name" : "pillar-id",
          "description" : "the unqiue identification code of the pillar under the classic view",
          "required" : true,
          "schema" : {
            "type" : "integer"
          },
          "example" : 2
        } ],
        "responses" : {
          "200" : {
            "description" : "return list of all indicators and summary of key indicators (top five) for a specific pillar under the classic view",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "pillarId" : {
                      "type" : "string",
                      "description" : "unique identification number of the pillar"
                    },
                    "pillarName" : {
                      "type" : "string",
                      "description" : "the name of the pillar"
                    },
                    "pillarIconLG" : {
                      "type" : "string",
                      "description" : "the icon associated with the pillar - large sized in base64 format"
                    },
                    "kpis" : {
                      "$ref" : "#/components/schemas/kpis"
                    },
                    "indicators" : {
                      "type" : "array",
                      "description" : "an array of indicators under the pillar",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "id" : {
                            "type" : "string",
                            "description" : "unqiue identification number of the indicator"
                          },
                          "name" : {
                            "type" : "string",
                            "description" : "the name of the indicator"
                          }
                        }
                      }
                    }
                  }
                },
                "example" : {
                  "pillarId" : "2",
                  "pillarName" : "الإعلام",
                  "pillarIconLG" : "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxODIuODQ4IiBoZWlnaHQ9IjEyOCIgdmlld0JveD0iMCAwIDE4Mi44NDggMTI4Ij4KICA8ZyBpZD0iaGVhbHRoIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLjA4MyAtMC4wMDUpIj4KICAgIDxwYXRoIGlkPSJfUGF0aF8zIiBkYXRhLW5hbWU9IiBQYXRoIDMiIGQ9Ik0zNDIuMTMyLDI1MS42ODJjMC03LjY3Ny00LjkxNS0xMy45MTYtMTIuMzktMTMuOTE2LTMuNzI5LDAtOC4yMzYsNC4wOTMtMTAuNjc5LDYuNi0yLjQ1NC0yLjUyMi02LjY0OC02LjYwOS0xMC4zNzEtNi42MDktNy40NTksMC0xMi42OTIsNi4yMjgtMTIuNjkyLDEzLjkyMmExNC4wNjcsMTQuMDY3LDAsMCwwLDMuOTU4LDkuODI0aDBsMTkuMTMzLDE5LjE2MSwxOS4xLTE5LjEzOGgwQTE0LjA2NywxNC4wNjcsMCwwLDAsMzQyLjEzMiwyNTEuNjgyWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE1OS4zNjggLTE4My45NTQpIiBmaWxsPSIjZmZmIi8+CiAgICA8ZyBpZD0iX0dyb3VwXyIgZGF0YS1uYW1lPSIgR3JvdXAgIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMC4wODMgMC4wMDUpIj4KICAgICAgPHBhdGggaWQ9Il9QYXRoXzQiIGRhdGEtbmFtZT0iIFBhdGggNCIgZD0iTTE1Mi44NzksMjY5LjUzNWgtLjJhMy4xMjUsMy4xMjUsMCwwLDEtMi45LTIuNmwtOS43MTctNTYuNi0xNC43MjEsMjcuMjlhMy4xNDIsMy4xNDIsMCwwLDEtNS44NzEtMS4wNDZMMTEzLjIyMSwxOTIuOWwtMTEuNDM0LDI1LjY4YTMuMTUzLDMuMTUzLDAsMCwxLTIuODY4LDEuODczSDU0LjQ4N2EzLjE0MiwzLjE0MiwwLDAsMSwwLTYuMjc5SDk2Ljg3OGwxNS4wNC0zMy44YTMuMTM3LDMuMTM3LDAsMCwxLDUuOTc3LjgxNmw2LjQ0Nyw0NS4wMzEsMTQuNTM3LTI2LjkxNmEzLjE0MiwzLjE0MiwwLDAsMSw1Ljg1OS45NjJsOS4wMDcsNTIuNDExLDMyLjc2OS0xMDguOTA5YTMuMTQyLDMuMTQyLDAsMCwxLDUuODM3LS40NThsMTcuMjYsMzUuNzgzYTMuMTQyLDMuMTQyLDAsMCwxLTUuNTkxLDIuODM1bC0uMDUtLjEwNi0xMy43NDktMjguNTE1TDE1NS44ODEsMjY3LjNhMy4xMzcsMy4xMzcsMCwwLDEtMywyLjIzNloiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC01MS40NzcgLTE0MS41MzUpIiBmaWxsPSIjZmZmIi8+CiAgICA8L2c+CiAgPC9nPgo8L3N2Zz4K",
                  "kpis" : [ {
                    "id" : "201",
                    "name" : "مؤشر حرية الصحافة",
                    "value" : "33.71",
                    "unit" : "نقطة",
                    "year" : "2022",
                    "rank" : "166",
                    "outOf" : "180",
                    "change" : "+2",
                    "scale" : "0-100",
                    "polarity" : "negative",
                    "trend" : [ "49.80", "45.10", "34.50", "35.60", "33.71" ]
                  } ],
                  "indicators" : [ {
                    "id" : "201",
                    "name" : "مؤشر حرية الصحافة"
                  }, {
                    "id" : "202",
                    "name" : "مؤشر الفجوة بين الجنسين"
                  }, {
                    "id" : "203",
                    "name" : "مؤشر الدول الجيدة"
                  } ]
                }
              }
            }
          },
          "204" : {
            "description" : "No Content"
          }
        }
      }
    },
    "/sdg/pillars/{pillar-id}/indicators" : {
      "get" : {
        "summary" : "List of indicators for a specific pillar under the SDG view",
        "description" : "Return list of all indicators and summary of key indicators (top five) for a specific pillar under the SDG view",
        "parameters" : [ {
          "in" : "path",
          "name" : "pillar-id",
          "description" : "the unqiue identification code of the pillar under the SDG view",
          "required" : true,
          "schema" : {
            "type" : "integer"
          },
          "example" : 111
        } ],
        "responses" : {
          "200" : {
            "description" : "return list of all indicators and summary of key indicators (top five) for a specific pillar under the SDG view",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "pillarId" : {
                      "type" : "string",
                      "description" : "unique identification number of the pillar"
                    },
                    "pillarName" : {
                      "type" : "string",
                      "description" : "the name of the pillar"
                    },
                    "pillarIconLG" : {
                      "type" : "string",
                      "description" : "the icon associated with the pillar - large sized in base64 format"
                    },
                    "kpis" : {
                      "$ref" : "#/components/schemas/kpis"
                    },
                    "indicators" : {
                      "type" : "array",
                      "description" : "an array of indicators under the pillar",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "id" : {
                            "type" : "string",
                            "description" : "the identification number of the indicator"
                          },
                          "name" : {
                            "type" : "string",
                            "description" : "the name of the indicator"
                          }
                        }
                      }
                    }
                  }
                },
                "example" : {
                  "pillarId" : "2",
                  "pillarName" : "الإعلام",
                  "pillarIconLG" : "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxODIuODQ4IiBoZWlnaHQ9IjEyOCIgdmlld0JveD0iMCAwIDE4Mi44NDggMTI4Ij4KICA8ZyBpZD0iaGVhbHRoIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLjA4MyAtMC4wMDUpIj4KICAgIDxwYXRoIGlkPSJfUGF0aF8zIiBkYXRhLW5hbWU9IiBQYXRoIDMiIGQ9Ik0zNDIuMTMyLDI1MS42ODJjMC03LjY3Ny00LjkxNS0xMy45MTYtMTIuMzktMTMuOTE2LTMuNzI5LDAtOC4yMzYsNC4wOTMtMTAuNjc5LDYuNi0yLjQ1NC0yLjUyMi02LjY0OC02LjYwOS0xMC4zNzEtNi42MDktNy40NTksMC0xMi42OTIsNi4yMjgtMTIuNjkyLDEzLjkyMmExNC4wNjcsMTQuMDY3LDAsMCwwLDMuOTU4LDkuODI0aDBsMTkuMTMzLDE5LjE2MSwxOS4xLTE5LjEzOGgwQTE0LjA2NywxNC4wNjcsMCwwLDAsMzQyLjEzMiwyNTEuNjgyWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE1OS4zNjggLTE4My45NTQpIiBmaWxsPSIjZmZmIi8+CiAgICA8ZyBpZD0iX0dyb3VwXyIgZGF0YS1uYW1lPSIgR3JvdXAgIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMC4wODMgMC4wMDUpIj4KICAgICAgPHBhdGggaWQ9Il9QYXRoXzQiIGRhdGEtbmFtZT0iIFBhdGggNCIgZD0iTTE1Mi44NzksMjY5LjUzNWgtLjJhMy4xMjUsMy4xMjUsMCwwLDEtMi45LTIuNmwtOS43MTctNTYuNi0xNC43MjEsMjcuMjlhMy4xNDIsMy4xNDIsMCwwLDEtNS44NzEtMS4wNDZMMTEzLjIyMSwxOTIuOWwtMTEuNDM0LDI1LjY4YTMuMTUzLDMuMTUzLDAsMCwxLTIuODY4LDEuODczSDU0LjQ4N2EzLjE0MiwzLjE0MiwwLDAsMSwwLTYuMjc5SDk2Ljg3OGwxNS4wNC0zMy44YTMuMTM3LDMuMTM3LDAsMCwxLDUuOTc3LjgxNmw2LjQ0Nyw0NS4wMzEsMTQuNTM3LTI2LjkxNmEzLjE0MiwzLjE0MiwwLDAsMSw1Ljg1OS45NjJsOS4wMDcsNTIuNDExLDMyLjc2OS0xMDguOTA5YTMuMTQyLDMuMTQyLDAsMCwxLDUuODM3LS40NThsMTcuMjYsMzUuNzgzYTMuMTQyLDMuMTQyLDAsMCwxLTUuNTkxLDIuODM1bC0uMDUtLjEwNi0xMy43NDktMjguNTE1TDE1NS44ODEsMjY3LjNhMy4xMzcsMy4xMzcsMCwwLDEtMywyLjIzNloiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC01MS40NzcgLTE0MS41MzUpIiBmaWxsPSIjZmZmIi8+CiAgICA8L2c+CiAgPC9nPgo8L3N2Zz4K",
                  "kpis" : [ {
                    "id" : "201",
                    "name" : "مؤشر حرية الصحافة",
                    "value" : "33.71",
                    "unit" : "نقطة",
                    "year" : "2022",
                    "rank" : "166",
                    "outOf" : "180",
                    "change" : "+2",
                    "scale" : "0-100",
                    "polarity" : "negative",
                    "trend" : [ "49.80", "45.10", "34.50", "35.60", "33.71" ]
                  } ],
                  "indicators" : [ {
                    "id" : "201",
                    "name" : "مؤشر حرية الصحافة"
                  }, {
                    "id" : "202",
                    "name" : "مؤشر الفجوة بين الجنسين"
                  }, {
                    "id" : "203",
                    "name" : "مؤشر الدول الجيدة"
                  } ]
                }
              }
            }
          },
          "204" : {
            "description" : "No Content"
          }
        }
      }
    },
    "/classic/pillars/{pillar-id}/indicators/{indicator-id}" : {
      "get" : {
        "summary" : "Detailed KPI information",
        "description" : "Return the KPI detailed information including country-wise measurement values for comparative analysis under the classic view",
        "parameters" : [ {
          "in" : "path",
          "name" : "pillar-id",
          "description" : "the unqiue identification code of the pillar under the classic view",
          "required" : true,
          "schema" : {
            "type" : "integer"
          },
          "example" : 2
        }, {
          "in" : "path",
          "name" : "indicator-id",
          "description" : "the unqiue identification code of the indicator under the pillar for classic view",
          "required" : true,
          "schema" : {
            "type" : "integer"
          },
          "example" : 201
        } ],
        "responses" : {
          "200" : {
            "description" : "return the KPI detailed information including country-wise measurement values for comparative analysis under the classic view",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "hasSubIndicators" : {
                      "type" : "boolean",
                      "description" : "indicates if the indicator has any sub-indicators"
                    },
                    "indicatorName" : {
                      "type" : "string",
                      "description" : "the name of the indicator"
                    },
                    "indicatorDescription" : {
                      "type" : "string",
                      "description" : "the description of the indicator"
                    },
                    "indicatorKSAValue" : {
                      "type" : "string",
                      "description" : "the latest value of the indicator for Saudi Arabia"
                    },
                    "indicatorUnit" : {
                      "type" : "string",
                      "description" : "the unit of measurement for the indicator"
                    },
                    "indicatorMeasurementYear" : {
                      "type" : "string",
                      "description" : "the year when the latest value of the indicator was captured - format YYYY"
                    },
                    "indicatorPolarity" : {
                      "type" : "string",
                      "description" : "the indicator polarity indicates its preferred direction - a \"positive\" polarity indicates higher values are preferable and a \"negative\" polarity indicates lower values are preferable"
                    },
                    "indicatorSourceName" : {
                      "type" : "string",
                      "description" : "the source name from which the indicator values are retrieved from"
                    },
                    "indicatorSourceLink" : {
                      "type" : "string",
                      "description" : "the URL link of source from which the indicator values are retrieved from"
                    },
                    "topCountry" : {
                      "type" : "string",
                      "description" : "the name of the country that secured the highest rank for this indicator"
                    },
                    "countries" : {
                      "type" : "array",
                      "description" : "the indicator measurements for all the countries and their trend values across the years",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "code" : {
                            "type" : "string",
                            "description" : "the country code"
                          },
                          "name" : {
                            "type" : "string",
                            "description" : "the name of the country"
                          },
                          "rank" : {
                            "type" : "string",
                            "description" : "the global rank of the country"
                          },
                          "outOfRank" : {
                            "type" : "string",
                            "description" : "the maximum range on which the indicator global rank is assigned"
                          },
                          "value" : {
                            "type" : "string",
                            "description" : "the value of the indicator for the country"
                          },
                          "unit" : {
                            "type" : "string",
                            "description" : "the unit of the indicator"
                          },
                          "rankChange" : {
                            "type" : "string",
                            "description" : "the change in rank of the country compared to the previous value"
                          },
                          "trend" : {
                            "type" : "array",
                            "description" : "the historical details of the measured indicator across the years",
                            "items" : {
                              "type" : "object",
                              "properties" : {
                                "value" : {
                                  "type" : "string",
                                  "description" : "the value of the indicator for the specific year"
                                },
                                "year" : {
                                  "type" : "string",
                                  "description" : "the year when the value was recorded for the indicator"
                                }
                              }
                            }
                          },
                          "countryGroup" : {
                            "type" : "array",
                            "description" : "an array which reflects the group(s) the country belongs to - world; g20;gcc;",
                            "items" : {
                              "type" : "string"
                            }
                          }
                        }
                      }
                    },
                    "subIndicators" : {
                      "$ref" : "#/components/schemas/kpis"
                    }
                  }
                },
                "example" : {
                  "hasSubIndicators" : true,
                  "indicatorName" : "مؤشر حرية الصحافة",
                  "indicatorDescription" : "حرية الصحافة هي الإمكانية الفعلية للصحفيين لاختيار وإنتاج ونشر المعلومات التي تصب في المصلحة العامة، بشكل مستقل عن التدخل السياسي والاقتصادي والقانوني والاجتماعي، ودون أي تهديدات ضد سلامتهم الجسدية والعقلية",
                  "indicatorKSAValue" : "33.71",
                  "indicatorUnit" : "نقطة",
                  "indicatorMeasurementYear" : "2022",
                  "indicatorPolarity" : "سالبة",
                  "indicatorSourceName" : "مراسلون بلا حدود",
                  "indicatorSourceLink" : "https://rsf.org/en/index",
                  "topCountry" : "النرويج",
                  "countries" : [ {
                    "code" : "NO",
                    "name" : "النرويج",
                    "rank" : "1",
                    "outOfRank" : "180",
                    "value" : "92.65",
                    "unit" : "نقطة",
                    "rankChange" : "+5",
                    "trend" : [ {
                      "value" : "90.5",
                      "year" : "2021"
                    }, {
                      "value" : "88.4",
                      "year" : "2020"
                    } ],
                    "countryGroup" : [ "W" ]
                  }, {
                    "code" : "SE",
                    "name" : "السويد",
                    "rank" : "3",
                    "outOfRank" : "180",
                    "value" : "88.84",
                    "unit" : "نقطة",
                    "rankChange" : "-1",
                    "trend" : [ {
                      "value" : "90.5",
                      "year" : "2021"
                    }, {
                      "value" : "85.4",
                      "year" : "2020"
                    } ],
                    "countryGroup" : [ "W", "G20" ]
                  }, {
                    "code" : "SA",
                    "name" : "المملكة العربية السعودية",
                    "rank" : "166",
                    "outOfRank" : "180",
                    "value" : "33.71",
                    "unit" : "نقطة",
                    "rankChange" : "+5",
                    "trend" : [ {
                      "value" : "80.5",
                      "year" : "2021"
                    }, {
                      "value" : "77.4",
                      "year" : "2020"
                    } ],
                    "countryGroup" : [ "W", "G20", "GCC" ]
                  } ],
                  "subIndicators" : [ {
                    "id" : "201.1",
                    "name" : "المؤشر السياسي",
                    "value" : "37.27",
                    "unit" : "نقطة",
                    "year" : "2022",
                    "rank" : "132",
                    "outOf" : "180",
                    "change" : "+2",
                    "scale" : "0-100",
                    "polarity" : "سالبة",
                    "trend" : [ "20.5", "22.5", "31.2", "33.9", "37.27" ]
                  }, {
                    "id" : "201.2",
                    "name" : "المؤشر الاقتصادي",
                    "value" : "33.67",
                    "unit" : "نقطة",
                    "year" : "2022",
                    "rank" : "132",
                    "outOf" : "180",
                    "change" : "-3",
                    "scale" : "0-100",
                    "polarity" : "سالبة",
                    "trend" : [ "21.1", "22.5", "29.2", "36.0", "33.67" ]
                  }, {
                    "id" : "201.3",
                    "name" : "المؤشر التشريعي",
                    "value" : "22.37",
                    "unit" : "نقطة",
                    "year" : "2022",
                    "rank" : "177",
                    "outOf" : "180",
                    "change" : "-5",
                    "scale" : "0-100",
                    "polarity" : "سالبة",
                    "trend" : [ "21.0", "21.4", "23.5", "28.1", "22.37" ]
                  }, {
                    "id" : "201.4",
                    "name" : "المؤشر الاجتماعي",
                    "value" : "36.5",
                    "unit" : "نقطة",
                    "year" : "2022",
                    "rank" : "167",
                    "outOf" : "180",
                    "rankChange" : "0",
                    "scale" : "0-100",
                    "polarity" : "سالبة",
                    "trend" : [ "31.0", "31.1", "35.0", "35.5", "36.5" ]
                  }, {
                    "id" : "201.5",
                    "name" : "مؤشر الأمن",
                    "value" : "38.75",
                    "unit" : "نقطة",
                    "year" : "2022",
                    "rank" : "138",
                    "outOf" : "180",
                    "rankChange" : "+1",
                    "scale" : "0-100",
                    "polarity" : "سالبة",
                    "trend" : [ "35.2", "37.7", "38.0", "38.5", "38.75" ]
                  } ]
                }
              }
            }
          }
        }
      }
    },
    "/sdg/pillars/{pillar-id}/indicators/{indicator-id}" : {
      "get" : {
        "summary" : "Detailed KPI information for indicators under the SDG view",
        "description" : "Return the KPI detailed information including country-wise measurement values for comparative analysis under the SDG view",
        "parameters" : [ {
          "in" : "path",
          "name" : "pillar-id",
          "description" : "the unqiue identification code of the pillar under the SDG view",
          "required" : true,
          "schema" : {
            "type" : "integer"
          },
          "example" : 111
        }, {
          "in" : "path",
          "name" : "indicator-id",
          "description" : "the unqiue identification code of the indicator under the pillar for SDG view",
          "required" : true,
          "schema" : {
            "type" : "integer"
          },
          "example" : 102
        } ],
        "responses" : {
          "200" : {
            "description" : "return the KPI detailed information including country-wise measurement values for comparative analysis under the SDG view",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "hasSubIndicators" : {
                      "type" : "boolean",
                      "description" : "indicates if the indicator has any sub-indicators"
                    },
                    "indicatorName" : {
                      "type" : "string",
                      "description" : "the name of the indicator"
                    },
                    "indicatorDescription" : {
                      "type" : "string",
                      "description" : "the description of the indicator"
                    },
                    "indicatorKSAValue" : {
                      "type" : "string",
                      "description" : "the latest value of the indicator for Saudi Arabia"
                    },
                    "indicatorUnit" : {
                      "type" : "string",
                      "description" : "the unit of measurement for the indicator"
                    },
                    "indicatorMeasurementYear" : {
                      "type" : "string",
                      "description" : "the year when the latest value of the indicator was captured - format YYYY"
                    },
                    "indicatorPolarity" : {
                      "type" : "string",
                      "description" : "the indicator polarity indicates its preferred direction - a \"positive\" polarity indicates higher values are preferable and a \"negative\" polarity indicates lower values are preferable"
                    },
                    "indicatorSourceName" : {
                      "type" : "string",
                      "description" : "the source name from which the indicator values are retrieved from"
                    },
                    "indicatorSourceLink" : {
                      "type" : "string",
                      "description" : "the URL link of source from which the indicator values are retrieved from"
                    },
                    "topCountry" : {
                      "type" : "string",
                      "description" : "the name of the country that secured the highest rank for this indicator"
                    },
                    "countries" : {
                      "type" : "array",
                      "description" : "the indicator measurements for all the countries and their trend values across the years",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "code" : {
                            "type" : "string",
                            "description" : "the country code"
                          },
                          "name" : {
                            "type" : "string",
                            "description" : "the name of the country"
                          },
                          "rank" : {
                            "type" : "string",
                            "description" : "the global rank of the country"
                          },
                          "outOfRank" : {
                            "type" : "string",
                            "description" : "the maximum range on which the indicator global rank is assigned"
                          },
                          "value" : {
                            "type" : "string",
                            "description" : "the value of the indicator for the country"
                          },
                          "unit" : {
                            "type" : "string",
                            "description" : "the unit of the indicator"
                          },
                          "rankChange" : {
                            "type" : "string",
                            "description" : "the change in rank of the country compared to the previous value"
                          },
                          "trend" : {
                            "type" : "array",
                            "description" : "the historical details of the measured indicator across the years",
                            "items" : {
                              "type" : "object",
                              "properties" : {
                                "value" : {
                                  "type" : "string",
                                  "description" : "the value of the indicator for the specific year"
                                },
                                "year" : {
                                  "type" : "string",
                                  "description" : "the year when the value was recorded for the indicator"
                                }
                              }
                            }
                          },
                          "countryGroup" : {
                            "type" : "array",
                            "description" : "an array which reflects the group(s) the country belongs to - world; g20;gcc;",
                            "items" : {
                              "type" : "string"
                            }
                          }
                        }
                      }
                    },
                    "subIndicators" : {
                      "$ref" : "#/components/schemas/kpis"
                    }
                  }
                },
                "example" : {
                  "hasSubIndicators" : true,
                  "indicatorName" : "مؤشر حرية الصحافة",
                  "indicatorDescription" : "حرية الصحافة هي الإمكانية الفعلية للصحفيين لاختيار وإنتاج ونشر المعلومات التي تصب في المصلحة العامة، بشكل مستقل عن التدخل السياسي والاقتصادي والقانوني والاجتماعي، ودون أي تهديدات ضد سلامتهم الجسدية والعقلية",
                  "indicatorKSAValue" : "33.71",
                  "indicatorUnit" : "نقطة",
                  "indicatorMeasurementYear" : "2022",
                  "indicatorPolarity" : "سالبة",
                  "indicatorSourceName" : "مراسلون بلا حدود",
                  "indicatorSourceLink" : "https://rsf.org/en/index",
                  "topCountry" : "النرويج",
                  "countries" : [ {
                    "code" : "NO",
                    "name" : "النرويج",
                    "rank" : "1",
                    "outOfRank" : "180",
                    "value" : "92.65",
                    "unit" : "نقطة",
                    "rankChange" : "+5",
                    "trend" : [ {
                      "value" : "90.5",
                      "year" : "2021"
                    }, {
                      "value" : "88.4",
                      "year" : "2020"
                    } ],
                    "countryGroup" : [ "W" ]
                  }, {
                    "code" : "SA",
                    "name" : "المملكة العربية السعودية",
                    "rank" : "166",
                    "outOfRank" : "180",
                    "value" : "33.71",
                    "unit" : "نقطة",
                    "rankChange" : "+5",
                    "trend" : [ {
                      "value" : "80.5",
                      "year" : "2021"
                    }, {
                      "value" : "77.4",
                      "year" : "2020"
                    } ],
                    "countryGroup" : [ "W", "G20", "GCC" ]
                  } ],
                  "subIndicators" : [ {
                    "id" : "201.1",
                    "name" : "المؤشر السياسي",
                    "value" : "37.27",
                    "unit" : "نقطة",
                    "year" : "2022",
                    "rank" : "132",
                    "outOf" : "180",
                    "change" : "+2",
                    "scale" : "0-100",
                    "polarity" : "سالبة",
                    "trend" : [ "20.5", "22.5", "31.2", "33.9", "37.27" ]
                  }, {
                    "id" : "201.2",
                    "name" : "المؤشر الاقتصادي",
                    "value" : "33.67",
                    "unit" : "نقطة",
                    "year" : "2022",
                    "rank" : "132",
                    "outOf" : "180",
                    "change" : "-3",
                    "scale" : "0-100",
                    "polarity" : "سالبة",
                    "trend" : [ "21.1", "22.5", "29.2", "36.0", "33.67" ]
                  } ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "kpis" : {
        "type" : "array",
        "description" : "collection of indicators/sub-indicators and associated details",
        "items" : {
          "type" : "object",
          "properties" : {
            "id" : {
              "type" : "string",
              "description" : "unique identification number of the KPI"
            },
            "name" : {
              "type" : "string",
              "description" : "the name of the KPI"
            },
            "value" : {
              "type" : "string",
              "description" : "the latest value of the KPI"
            },
            "unit" : {
              "type" : "string",
              "description" : "the unit of measurement for the KPI"
            },
            "year" : {
              "type" : "string",
              "description" : "the year when the latest value of the KPI was captured - format YYYY"
            },
            "rank" : {
              "type" : "string",
              "description" : "the global rank of the KPI"
            },
            "outOf" : {
              "type" : "string",
              "description" : "the maximum range on which the KPI global rank is assigned"
            },
            "change" : {
              "type" : "string",
              "description" : "the percentage change in the rank from the previous measurement of the KPI - positive or negative value"
            },
            "scale" : {
              "type" : "string",
              "description" : "the scale on which the KPI value is captured"
            },
            "polarity" : {
              "type" : "string",
              "description" : "the KPI polarity indicates its preferred direction - a \"positive\" polarity indicates higher values are preferable and a \"negative\" polarity indicates lower values are preferable"
            },
            "trend" : {
              "type" : "array",
              "description" : "array of the last five measured values in ascending order (latest value last)",
              "items" : {
                "type" : "string"
              }
            }
          }
        }
      }
    }
  },
  "servers" : [ {
    "description" : "SwaggerHub API Auto Mocking",
    "url" : "https://virtserver.swaggerhub.com/SolutionsBy42/iph/1.0"
  } ]
}